[package]
name = "diffsecp_inprocess"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[lib]
crate-type = ["staticlib"]

[dependencies]
libafl.workspace = true
libafl_bolts.workspace = true
# src/cmp.c replaces sancov_cmplog and sancov_value_profile.
libafl_targets = { workspace = true, features = ["sancov_8bit", "libfuzzer", "observers"] }
clap.workspace = true

[build-dependencies]
cc = "1"
