/* libFuzzer entry point for one target, chosen at compile time with
 * DIFFSECP_TARGET. Runs each input through every variant and aborts on the first
 * transcript mismatch, so libFuzzer saves the input as a reproducer. Then runs
 * the mutant schemata (mutants/) to see which mutants the input exposes. */

#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "diffsecp.h"
#include "mutants.h"  /* Generated by mutants/gen.py. */
#include "variants.h" /* Generated from variants.mk. */

#ifndef DIFFSECP_TARGET
#error "DIFFSECP_TARGET must be set to a member of struct diffsecp_variant"
#endif

#define DECLARE(name) extern const struct diffsecp_variant diffsecp_variant_##name;
DIFFSECP_VARIANTS(DECLARE)
DECLARE(mutant)
#undef DECLARE

#define ENTRY(name) &diffsecp_variant_##name,
static const struct diffsecp_variant *const variants[] = {DIFFSECP_VARIANTS(ENTRY)};
#undef ENTRY

#define NVARIANTS (sizeof(variants) / sizeof(variants[0]))

static unsigned char transcripts[NVARIANTS][DIFFSECP_TRANSCRIPT_MAX];
static size_t lengths[NVARIANTS];

/* The mutant schemata runs once with no mutant on, flagging in
 * diffsecp_mutant_infected each mutant the input's values trigger, then once per
 * flagged mutant not yet killed, which it kills if the transcript differs or an
 * API call rejects its arguments (diffsecp_mutant_illegal). Both arrays sit in
 * libFuzzer's extra counters, so an input that triggers or kills a new mutant
 * counts as new coverage. */
int diffsecp_mutant = DIFFSECP_MUTANT_DETECT;
int diffsecp_mutant_illegal;
unsigned char diffsecp_mutant_infected[DIFFSECP_MUTANT_COUNT]
    __attribute__((section("__libfuzzer_extra_counters")));
unsigned char diffsecp_mutant_killed[DIFFSECP_MUTANT_COUNT]
    __attribute__((section("__libfuzzer_extra_counters")));

static const char *const mutant_names[] = DIFFSECP_MUTANT_NAMES;
static unsigned char mutant_transcript[DIFFSECP_TRANSCRIPT_MAX];
static unsigned char mutant_ever_infected[DIFFSECP_MUTANT_COUNT];
static unsigned char mutant_ever_killed[DIFFSECP_MUTANT_COUNT];
/* DIFFSECP_MUTANTS=off skips the schemata, so evaluations can fuzz without its
 * feedback; =report prints what each mutant reached at exit. */
static int mutants_off;

int LLVMFuzzerInitialize(int *argc, char ***argv);
int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size);

static void dump(const char *name, const unsigned char *t, size_t len, size_t at) {
    size_t lo = at > 16 ? at - 16 : 0;
    size_t hi = at + 48 < len ? at + 48 : len;
    size_t i;

    fprintf(stderr, "  %-16s [%zu, %zu):", name, lo, hi);
    for (i = lo; i < hi; i++) {
        fprintf(stderr, "%s%02x", i == at ? " >" : " ", t[i]);
    }
    fputc('\n', stderr);
}

static int matches_reference(const unsigned char *t, size_t len) {
    return len == lengths[0] && memcmp(t, transcripts[0], len) == 0;
}

static void report_divergence(const char *name, const unsigned char *t, size_t len) {
    size_t n = lengths[0] < len ? lengths[0] : len;
    size_t at = 0;

    while (at < n && transcripts[0][at] == t[at]) {
        at++;
    }
    fprintf(stderr, "diffsecp: target %s diverges between %s and %s at byte %zu (lengths %zu, %zu)\n",
            DIFFSECP_STR(DIFFSECP_TARGET), variants[0]->name, name, at, lengths[0], len);
    dump(variants[0]->name, transcripts[0], lengths[0], at);
    dump(name, t, len, at);
    abort();
}

/* Mutants are killed, masked (the input's values triggered the mutant but no
 * transcript showed it) or missed (no input reached the values). */
static void report_mutants(void) {
    size_t k;

    for (k = 0; k < DIFFSECP_MUTANT_COUNT; k++) {
        printf("mutant %zu %s %s\n", k,
               mutant_ever_killed[k] ? "killed" : mutant_ever_infected[k] ? "masked" : "missed", mutant_names[k]);
    }
}

static void run_mutants(const uint8_t *data, size_t size) {
    size_t k, len;

    memset(diffsecp_mutant_infected, 0, sizeof(diffsecp_mutant_infected));
    diffsecp_mutant = DIFFSECP_MUTANT_DETECT;
    diffsecp_mutant_illegal = 0;
    len = diffsecp_variant_mutant.DIFFSECP_TARGET(data, size, mutant_transcript, sizeof(mutant_transcript));
    /* With no mutant on, the schemata is one more build that must agree. */
    if (diffsecp_mutant_illegal) {
        fprintf(stderr, "diffsecp: target %s calls the API illegally in %s with no mutant on\n",
                DIFFSECP_STR(DIFFSECP_TARGET), diffsecp_variant_mutant.name);
        abort();
    }
    if (!matches_reference(mutant_transcript, len)) {
        report_divergence(diffsecp_variant_mutant.name, mutant_transcript, len);
    }

    for (k = 0; k < DIFFSECP_MUTANT_COUNT; k++) {
        if (!diffsecp_mutant_infected[k]) {
            continue;
        }
        mutant_ever_infected[k] = 1;
        if (mutant_ever_killed[k]) {
            continue;
        }
        diffsecp_mutant = (int)k;
        len = diffsecp_variant_mutant.DIFFSECP_TARGET(data, size, mutant_transcript, sizeof(mutant_transcript));
        diffsecp_mutant = DIFFSECP_MUTANT_DETECT;
        if (diffsecp_mutant_illegal || !matches_reference(mutant_transcript, len)) {
            diffsecp_mutant_killed[k] = 1;
            mutant_ever_killed[k] = 1;
        }
    }
}

int LLVMFuzzerInitialize(int *argc, char ***argv) {
    const char *mode = getenv("DIFFSECP_MUTANTS");
    size_t i;

    (void)argc;
    (void)argv;
    if (mode != NULL && strcmp(mode, "off") == 0) {
        mutants_off = 1;
    } else if (mode != NULL && strcmp(mode, "report") == 0) {
        atexit(report_mutants);
    } else if (mode != NULL && mode[0] != '\0') {
        fprintf(stderr, "diffsecp: DIFFSECP_MUTANTS must be off, report or unset\n");
        exit(1);
    }
    for (i = 0; i < NVARIANTS; i++) {
        variants[i]->init();
    }
    diffsecp_variant_mutant.init();
    return 0;
}

int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size) {
    static const unsigned char empty[1];
    size_t i;

    if (size > DIFFSECP_INPUT_MAX) {
        return -1;
    }
    /* libsecp rejects null buffers even when empty, which would trip its illegal callback. */
    if (data == NULL) {
        data = empty;
    }

    for (i = 0; i < NVARIANTS; i++) {
        lengths[i] = variants[i]->DIFFSECP_TARGET(data, size, transcripts[i], DIFFSECP_TRANSCRIPT_MAX);
    }
    for (i = 1; i < NVARIANTS; i++) {
        if (!matches_reference(transcripts[i], lengths[i])) {
            report_divergence(variants[i]->name, transcripts[i], lengths[i]);
        }
    }
    if (!mutants_off) {
        run_mutants(data, size);
    }
    return 0;
}
