/* libFuzzer entry point for one target, chosen at compile time with
 * DIFFSECP_TARGET. Runs each input through every variant and aborts on the first
 * transcript mismatch, so libFuzzer saves the input as a reproducer. Then runs
 * the mutant schemata (mutants/) to see which mutants the input exposes. */

#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "diffsecp.h"
#include "digest.h"
#include "mutants.h"  /* Generated by mutants/gen.py. */
#include "variants.h" /* Generated from variants.mk. */

#ifndef DIFFSECP_TARGET
#error "DIFFSECP_TARGET must be set to a member of struct diffsecp_variant"
#endif

#define DECLARE(name) extern const struct diffsecp_variant diffsecp_variant_##name;
DIFFSECP_VARIANTS(DECLARE)
DIFFSECP_MUTANT_BUILDS(DECLARE)
#undef DECLARE

#define ENTRY(name) &diffsecp_variant_##name,
static const struct diffsecp_variant *const variants[] = {DIFFSECP_VARIANTS(ENTRY)};
static const struct diffsecp_variant *const mutant_builds[] = {DIFFSECP_MUTANT_BUILDS(ENTRY)};
#undef ENTRY

#define NVARIANTS (sizeof(variants) / sizeof(variants[0]))
#define NMUTANT_BUILDS (sizeof(mutant_builds) / sizeof(mutant_builds[0]))

static unsigned char transcripts[NVARIANTS][DIFFSECP_TRANSCRIPT_MAX];
static size_t lengths[NVARIANTS];

/* For fuzzers that link this driver (libafl/), which otherwise grow inputs past it. */
const size_t diffsecp_input_max = DIFFSECP_INPUT_MAX;

/* The digest of the last input's reference transcript, which every build
 * agreed with, for libafl/'s oracle to compare with other architectures. */
uint64_t diffsecp_reference_digest(void);

uint64_t diffsecp_reference_digest(void) {
    return diffsecp_digest(transcripts[0], lengths[0]);
}

/* Each mutant schemata build runs once with no mutant on, flagging in
 * diffsecp_mutant_infected each mutant the input's values trigger in its code,
 * then once per flagged mutant not yet killed, which it kills if the transcript
 * differs or an API call rejects its arguments (diffsecp_mutant_illegal). Both
 * arrays sit in libFuzzer's extra counters, so an input that triggers or kills a
 * new mutant counts as new coverage. */
int diffsecp_mutant = DIFFSECP_MUTANT_DETECT;
int diffsecp_mutant_illegal;
unsigned char diffsecp_mutant_infected[DIFFSECP_MUTANT_COUNT]
    __attribute__((section("__libfuzzer_extra_counters")));
unsigned char diffsecp_mutant_killed[DIFFSECP_MUTANT_COUNT]
    __attribute__((section("__libfuzzer_extra_counters")));
/* The arrays' length, for fuzzers that observe them by name (libafl/). */
const size_t diffsecp_mutant_count = DIFFSECP_MUTANT_COUNT;

/* Where the reference build read each operand of at least 32 bytes in the last
 * input, which libafl/ mutates as 256-bit numbers. A read may run past the end
 * of the input, which the mutator then extends. guide_CFLAGS routes every read
 * here with -DDIFFSECP_NOTE_READS. */
#define DIFFSECP_READS_MAX 256
struct diffsecp_read {
    uint32_t offset;
    uint32_t len;
};
struct diffsecp_read diffsecp_reads[DIFFSECP_READS_MAX];
size_t diffsecp_nreads;
/* The input while the reference runs, else NULL: the other builds read the same. */
static const unsigned char *reads_base;

static const char *const mutant_names[] = DIFFSECP_MUTANT_NAMES;
static unsigned char mutant_transcript[DIFFSECP_TRANSCRIPT_MAX];
static unsigned char mutant_ever_infected[DIFFSECP_MUTANT_COUNT];
static unsigned char mutant_ever_killed[DIFFSECP_MUTANT_COUNT];
/* DIFFSECP_MUTANTS=off skips the schemata, so evaluations can fuzz without its
 * feedback; =report prints what each mutant reached at exit. */
static int mutants_off;

int LLVMFuzzerInitialize(int *argc, char ***argv);
int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size);
void diffsecp_note_read(const unsigned char *p, size_t n);

void diffsecp_note_read(const unsigned char *p, size_t n) {
    if (reads_base != NULL && n >= 32 && diffsecp_nreads < DIFFSECP_READS_MAX) {
        diffsecp_reads[diffsecp_nreads].offset = (uint32_t)(p - reads_base);
        diffsecp_reads[diffsecp_nreads].len = (uint32_t)n;
        diffsecp_nreads++;
    }
}

static void dump(const char *name, const unsigned char *t, size_t len, size_t at) {
    size_t lo = at > 16 ? at - 16 : 0;
    size_t hi = at + 48 < len ? at + 48 : len;
    size_t i;

    fprintf(stderr, "  %-16s [%zu, %zu):", name, lo, hi);
    for (i = lo; i < hi; i++) {
        fprintf(stderr, "%s%02x", i == at ? " >" : " ", t[i]);
    }
    fputc('\n', stderr);
}

static int matches_reference(const unsigned char *t, size_t len) {
    return len == lengths[0] && memcmp(t, transcripts[0], len) == 0;
}

static void report_divergence(const char *name, const unsigned char *t, size_t len) {
    size_t n = lengths[0] < len ? lengths[0] : len;
    size_t at = 0;

    while (at < n && transcripts[0][at] == t[at]) {
        at++;
    }
    fprintf(stderr, "diffsecp: target %s diverges between %s and %s at byte %zu (lengths %zu, %zu)\n",
            DIFFSECP_STR(DIFFSECP_TARGET), variants[0]->name, name, at, lengths[0], len);
    dump(variants[0]->name, transcripts[0], lengths[0], at);
    dump(name, t, len, at);
    abort();
}

/* Mutants are killed, masked (the input's values triggered the mutant but no
 * transcript showed it) or missed (no input reached the values). */
static void report_mutants(void) {
    size_t k;

    for (k = 0; k < DIFFSECP_MUTANT_COUNT; k++) {
        printf("mutant %zu %s %s\n", k,
               mutant_ever_killed[k] ? "killed" : mutant_ever_infected[k] ? "masked" : "missed", mutant_names[k]);
    }
}

static size_t run_schemata(const struct diffsecp_variant *build, int mutant, const uint8_t *data, size_t size) {
    size_t len;

    diffsecp_mutant = mutant;
    diffsecp_mutant_illegal = 0;
    len = build->DIFFSECP_TARGET(data, size, mutant_transcript, sizeof(mutant_transcript));
    diffsecp_mutant = DIFFSECP_MUTANT_DETECT;
    return len;
}

static void run_mutants(const uint8_t *data, size_t size) {
    unsigned char infected[DIFFSECP_MUTANT_COUNT] = {0};
    size_t b, k, len;

    for (b = 0; b < NMUTANT_BUILDS; b++) {
        const struct diffsecp_variant *build = mutant_builds[b];

        memset(diffsecp_mutant_infected, 0, sizeof(diffsecp_mutant_infected));
        len = run_schemata(build, DIFFSECP_MUTANT_DETECT, data, size);
        /* With no mutant on, a schemata build is one more build that must agree. */
        if (diffsecp_mutant_illegal) {
            fprintf(stderr, "diffsecp: target %s calls the API illegally in %s with no mutant on\n",
                    DIFFSECP_STR(DIFFSECP_TARGET), build->name);
            abort();
        }
        if (!matches_reference(mutant_transcript, len)) {
            report_divergence(build->name, mutant_transcript, len);
        }

        for (k = 0; k < DIFFSECP_MUTANT_COUNT; k++) {
            if (!diffsecp_mutant_infected[k]) {
                continue;
            }
            infected[k] = 1;
            mutant_ever_infected[k] = 1;
            if (mutant_ever_killed[k]) {
                continue;
            }
            len = run_schemata(build, (int)k, data, size);
            if (diffsecp_mutant_illegal || !matches_reference(mutant_transcript, len)) {
                diffsecp_mutant_killed[k] = 1;
                mutant_ever_killed[k] = 1;
            }
        }
    }
    /* What the fuzzer observes: the mutants any build flagged. */
    memcpy(diffsecp_mutant_infected, infected, sizeof(infected));
}

int LLVMFuzzerInitialize(int *argc, char ***argv) {
    const char *mode = getenv("DIFFSECP_MUTANTS");
    size_t i;

    (void)argc;
    (void)argv;
    if (mode != NULL && strcmp(mode, "off") == 0) {
        mutants_off = 1;
    } else if (mode != NULL && strcmp(mode, "report") == 0) {
        atexit(report_mutants);
    } else if (mode != NULL && mode[0] != '\0') {
        fprintf(stderr, "diffsecp: DIFFSECP_MUTANTS must be off, report or unset\n");
        exit(1);
    }
    for (i = 0; i < NVARIANTS; i++) {
        variants[i]->init();
    }
    for (i = 0; i < NMUTANT_BUILDS; i++) {
        mutant_builds[i]->init();
    }
    return 0;
}

int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size) {
    static const unsigned char empty[1];
    size_t i;

    if (size > DIFFSECP_INPUT_MAX) {
        return -1;
    }
    /* libsecp rejects null buffers even when empty, which would trip its illegal callback. */
    if (data == NULL) {
        data = empty;
    }

    diffsecp_nreads = 0;
    for (i = 0; i < NVARIANTS; i++) {
        reads_base = i == 0 ? data : NULL;
        lengths[i] = variants[i]->DIFFSECP_TARGET(data, size, transcripts[i], DIFFSECP_TRANSCRIPT_MAX);
    }
    reads_base = NULL;
    for (i = 1; i < NVARIANTS; i++) {
        if (!matches_reference(transcripts[i], lengths[i])) {
            report_divergence(variants[i]->name, transcripts[i], lengths[i]);
        }
    }
    if (!mutants_off) {
        run_mutants(data, size);
    }
    return 0;
}
